name: Python tests
on: [push]
env:
  GITHUB_ACTIONS: 1

jobs:
  ubuntu_firefox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.5, 3.6, 3.7, 3.8]
        django: [110, 1tip, 20, 21, 22, 30, tip]
        drf: [38, 39, 310, tip]
        include:
          - { django: 110, drf: 3.6 }
          - { django: 1tip, drf: 3.7 }
      fail-fast: false

    env:
      BROWSER_SELENIUM: 'FIREFOX;{"headless": true, "binary_location": "/usr/bin/firefox"}'

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Prepare Selenium enviroment
        run: |
          #Download geckodriver
          wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
          #Extract geckodriver
          tar -xvzf geckodriver*
          #Make geckodriver execuable
          chmod +x geckodriver
          #Move geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Run Tox py-django{{ matrix.django }}-drf{{ matrix.drf }}
        run: tox -e py-django{{ matrix.django }}-drf{{ matrix.drf }}
        if: success() || failure()
        continue-on-error: {{ matrix.drf }} == 'drftip'


  ubuntu_chrome:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7]
      fail-fast: false

    env:
      BROWSER_SELENIUM: 'CHROME;{"no-sandbox": true, "window-size": "1420,1080", "headless": true, "disable-gpu": true}'

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox

      - name: Run Tox py-django110-drf36
        run: tox -e py-django110-drf36
        continue-on-error: true

      - name: Run Tox py-django110-drf39
        if: success() || failure()
        run: tox -e py-django110-drf39
        continue-on-error: true

      - name: Run Tox py-django1tip-drf37
        if: success() || failure()
        run: tox -e py-django1tip-drf37
        continue-on-error: true

      - name: Run Tox py-django1tip-drf38
        if: success() || failure()
        run: tox -e py-django1tip-drf38
        continue-on-error: true

      - name: Run Tox py-django1tip-drf39
        if: success() || failure()
        run: tox -e py-django1tip-drf39
        continue-on-error: true

      - name: Run Tox py-django1tip-drftip
        if: success() || failure()
        continue-on-error: true
        run: tox -e py-django1tip-drftip

      - name: Run Tox py-django20-drf39
        if: success() || failure()
        run: tox -e py-django20-drf39
        continue-on-error: true

      - name: Run Tox py-django21-drf39
        if: success() || failure()
        run: tox -e py-django21-drf39
        continue-on-error: true

      - name: Run Tox py-django22-drf39
        if: success() || failure()
        run: tox -e py-django22-drf39
        continue-on-error: true

      - name: Run Tox py-django22-drf38
        if: success() || failure()
        run: tox -e py-django22-drf38
        continue-on-error: true

      - name: Run Tox py-django22-drftip
        if: success() || failure()
        continue-on-error: true
        run: tox -e py-django22-drftip

      - name: Run Tox py-djangotip-drftip
        if: success() || failure()
        continue-on-error: true
        run: tox -e py-djangotip-drftip

  macos_safari:
    runs-on: macos-latest
    strategy:
      matrix:
        python: [3.7]
      fail-fast: false

    # Da bodo delali fukcionalni testi v Safariju morajo najprej urediti issue https://github.com/actions/virtual-environments/issues/91
    env:
      BROWSER_SELENIUM: 'SAFARI'

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox py-django110-drf36
        run: tox -e py-django110-drf36
        continue-on-error: true

      - name: Run Tox py-django110-drf39
        if: success() || failure()
        run: tox -e py-django110-drf39
        continue-on-error: true

      - name: Run Tox py-django1tip-drf37
        if: success() || failure()
        run: tox -e py-django1tip-drf37
        continue-on-error: true

      - name: Run Tox py-django1tip-drf38
        if: success() || failure()
        run: tox -e py-django1tip-drf38
        continue-on-error: true

      - name: Run Tox py-django1tip-drf39
        if: success() || failure()
        run: tox -e py-django1tip-drf39
        continue-on-error: true

      - name: Run Tox py-django1tip-drftip
        if: success() || failure()
        continue-on-error: true
        run: tox -e py-django1tip-drftip

      - name: Run Tox py-django20-drf39
        if: success() || failure()
        run: tox -e py-django20-drf39
        continue-on-error: true

      - name: Run Tox py-django21-drf39
        if: success() || failure()
        run: tox -e py-django21-drf39
        continue-on-error: true

      - name: Run Tox py-django22-drf39
        if: success() || failure()
        run: tox -e py-django22-drf39
        continue-on-error: true

      - name: Run Tox py-django22-drf38
        if: success() || failure()
        run: tox -e py-django22-drf38
        continue-on-error: true

      - name: Run Tox py-django22-drftip
        if: success() || failure()
        continue-on-error: true
        run: tox -e py-django22-drftip

      - name: Run Tox py-djangotip-drftip
        if: success() || failure()
        continue-on-error: true
        run: tox -e py-djangotip-drftip

  win_edge:
    runs-on: windows-latest
    strategy:
      matrix:
        python: [3.7]
      fail-fast: false

    # Da bodo delali fukcionalni testi v Edge-ju morajo najprej urediti issue https://github.com/actions/virtual-environments/issues/99
    env:
      BROWSER_SELENIUM: 'EDGE'

    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox and any other packages
        run: pip install tox
      - name: Run Tox py-django110-drf36
        run: tox -e py-django110-drf36
        continue-on-error: true

      - name: Run Tox py-django110-drf39
        if: success() || failure()
        run: tox -e py-django110-drf39
        continue-on-error: true

      - name: Run Tox py-django1tip-drf37
        if: success() || failure()
        run: tox -e py-django1tip-drf37
        continue-on-error: true

      - name: Run Tox py-django1tip-drf38
        if: success() || failure()
        run: tox -e py-django1tip-drf38
        continue-on-error: true

      - name: Run Tox py-django1tip-drf39
        if: success() || failure()
        run: tox -e py-django1tip-drf39
        continue-on-error: true

      - name: Run Tox py-django1tip-drftip
        if: success() || failure()
        continue-on-error: true
        run: tox -e py-django1tip-drftip

      - name: Run Tox py-django20-drf39
        if: success() || failure()
        run: tox -e py-django20-drf39
        continue-on-error: true

      - name: Run Tox py-django21-drf39
        if: success() || failure()
        run: tox -e py-django21-drf39
        continue-on-error: true

      - name: Run Tox py-django22-drf39
        if: success() || failure()
        run: tox -e py-django22-drf39
        continue-on-error: true

      - name: Run Tox py-django22-drf38
        if: success() || failure()
        run: tox -e py-django22-drf38
        continue-on-error: true

      - name: Run Tox py-django22-drftip
        if: success() || failure()
        continue-on-error: true
        run: tox -e py-django22-drftip

      - name: Run Tox py-djangotip-drftip
        if: success() || failure()
        continue-on-error: true
        run: tox -e py-djangotip-drftip
